챌린지 리스트 sort API 연결
2-Docthru-team1/2-Docthru-team1-FE pull request #150
Opened 2024-11-27 10:29 UTC by galaxy-78

## 이슈 번호

- close #138 

## 작업 사항
- [x] 챌린지 리스트 sort API 연결
  - filterbar css 날아간 문제 해결
  - css 전체 수정
  - reset, apply 구현
  - 미디어타입 취소 안되는거 구현
  - 미디어타입 중복 전송 안되는거 구현
- [x] challenge list 페이지에서 챌린지 요청 버튼 어드민 로그인 때 없애기

## 기타
- modal에 abort reason 쓰는 input 집어넣기
  - 그러면 API 바로 작동 가능
- 어드민챌린지는 백엔드 API 완성되어야 할 수 있음.
  - 새로운 타입 지정 ?
- 현재 프론트에서 onGoing, finished로 걸러주고 있는데, 리스트 받아오는데 문제가 생겨서 백엔드 측에서 만들어주면 아래와 같이 수정.
  - 챌린지 리스트 페이지 / 어드민 관리 페이지 두개로 API 나눠서 하기

2024-11-27 14:12 UTC, hyobiin9 requested changes

2024-11-27 14:12 UTC, hyobiin9 commented on src/components/FilterBar/FilterBar.tsx
> +      <div className="">
요 부분 그냥 `<div>`로만 남겨주세요!

2024-11-27 14:16 UTC, LDY981212 approved these changes

2024-11-28 00:08 UTC, galaxy-78 commented on src/components/FilterBar/FilterBar.tsx
> +      <div className="">
반영했습니다 !

2024-11-28 00:08 UTC, merged