작업물 페이지 작업물 컴포넌트
2-Docthru-team1/2-Docthru-team1-FE pull request #51
Opened 2024-11-19 04:57 UTC by LDY981212

작업물 UI 생성

## 이슈 번호

- close #46 

## 작업 사항

## 기타

2024-11-19 09:56 UTC, hyobiin9 requested changes
수고하셨습니다!

2024-11-19 09:56 UTC, hyobiin9 commented on src/stories/WorkCard.stories.tsx
> +} as Meta<WorkDataProps>;
as는 들어오는 데이터가 어떻든 무조건 이 타입으로만 고정하겠다는 의미라서
`as Meta` 요 부분이 꼭 필요한 게 아니라면 삭제해주시면 좋을 것 같습니다!

2024-11-19 09:56 UTC, hyobiin9 commented on src/components/Card/WorkCard.tsx
> +          <Image src={food} alt="작업물 이미지" fill className="object-cover" onClick={openImg} />{' '}
여기에 빈 문자는 어떤 용도인가요?

2024-11-19 09:56 UTC, hyobiin9 commented on src/components/Card/WorkCard.tsx
> +          {/* src={data.images[currentOrder]} */}
이 주석은 어떤 용도인가요?

2024-11-19 09:56 UTC, hyobiin9 commented on src/components/Card/WorkCard.tsx
> +            <Image src={food} alt="작업물 확대 이미지" fill className="object-cover" /> {/* src={data.images[currentOrder]} */}
여기 주석은 어떤 용도인가요??

2024-11-19 09:58 UTC, LDY981212 commented on src/components/Card/WorkCard.tsx
> +          <Image src={food} alt="작업물 이미지" fill className="object-cover" onClick={openImg} />{' '}
오타인 것 같습니다!

2024-11-19 10:00 UTC, LDY981212 commented on src/components/Card/WorkCard.tsx
> +          {/* src={data.images[currentOrder]} */}
지금은 css를 위해서 디렉토리 안에 있는 이미지를 사용해서 나타냈는데 추후 데이터를 받아서 사용할 때 사용하기 위해서 주석으로 남겨놨습니다!

2024-11-19 10:01 UTC, LDY981212 commented on src/components/Card/WorkCard.tsx
> +            <Image src={food} alt="작업물 확대 이미지" fill className="object-cover" /> {/* src={data.images[currentOrder]} */}
위 주석과 같은 이유입니다!

2024-11-19 10:01 UTC, LDY981212 commented on src/stories/WorkCard.stories.tsx
> +} as Meta<WorkDataProps>;
넵 알겠습니다!

2024-11-19 10:51 UTC, galaxy-78 reviewed
나머지는 딱히 없는 것 같습니다 !

2024-11-19 10:51 UTC, galaxy-78 commented on src/components/Card/WorkCard.tsx
> +    second
second=1 도 하면 좋을거 같습니다.

2024-11-20 00:51 UTC, galaxy-78 approved these changes

2024-11-20 00:55 UTC, hyobiin9 approved these changes

2024-11-20 00:57 UTC, merged