이미지 확대 모달 제작
2-Docthru-team1/2-Docthru-team1-FE pull request #74
Opened 2024-11-20 08:01 UTC by LDY981212

이미지 확대 모달 제작

## 이슈 번호

- close #73 

## 작업 사항

## 기타

다음에 할 작업
- 작업물 페이지의 피드백 컴포넌트 제작

2024-11-20 08:05 UTC, hyobiin9 requested changes

2024-11-20 08:05 UTC, hyobiin9 commented on src/components/Modal/ImageEnlargeModal.tsx
> +        <Image src={src} alt={alt} fill className="object-cover" /> {/* src={data.images[currentOrder]} */}
이런 부분은 코드 내부에 NOTE 또는 TODO를 사용하셔서 나중에 수정에 용이하게 만들어주시면 좋을 것 같아요!

2024-11-20 08:05 UTC, hyobiin9 commented on src/components/Card/WorkCard.tsx
> +        /* <ImageEnlargeModal src={data.images[currentOrder] alt="작업물 이미지" onClose={closeImg} /> */
이런 부분은 코드 내부에 NOTE 또는 TODO를 사용하셔서 나중에 수정에 용이하게 만들어주시면 좋을 것 같아요!

2024-11-20 09:01 UTC, galaxy-78 approved these changes
모달화 잘 하신거 같습니다.

2024-11-20 09:29 UTC, LDY981212 commented on src/components/Modal/ImageEnlargeModal.tsx
> +        <Image src={src} alt={alt} fill className="object-cover" /> {/* src={data.images[currentOrder]} */}
수정사항 반영했습니다!

2024-11-20 09:29 UTC, LDY981212 commented on src/components/Card/WorkCard.tsx
> +        /* <ImageEnlargeModal src={data.images[currentOrder] alt="작업물 이미지" onClose={closeImg} /> */
수정사항 반영했습니다!

2024-11-21 06:38 UTC, hyobiin9 approved these changes

2024-11-21 06:41 UTC, merged