작업물 페이지
2-Docthru-team1/2-Docthru-team1-FE pull request #83
Opened 2024-11-21 09:48 UTC by LDY981212

## 이슈 번호

- close #80 

## 작업 사항

## 기타

2024-11-21 12:33 UTC, MCprotein commented on src/api/api.ts
> +    }
@LDY981212 이거 필요한 코드인가요?

2024-11-25 09:33 UTC, MCprotein commented
도엽님 이거 pr 올려놓고 개발하시는건가요??

2024-11-25 09:36 UTC, LDY981212 commented
> 도엽님 이거 pr 올려놓고 개발하시는건가요??

넵 맞습니다! pr 올리고 개발하기로 해서 올리고 진행하고 있었습니다!

2024-11-26 05:34 UTC, hyobiin9 requested changes

2024-11-26 05:34 UTC, hyobiin9 commented on src/api/feedbackService.ts
> +};
요고 혹시 그냥 `workService.ts` 파일에서 진행 가능하실까요??
/works로 똑같이 시작되는 건 그냥 거기서 사용해야 나중에 찾기 편할 것 같아서요!

2024-11-26 05:34 UTC, hyobiin9 commented on src/components/Input/WorkInput.tsx
>    const handleChange = (e: ChangeEvent<HTMLTextAreaElement>): void => {
이 부분 :void를 꼭 써야 하는건가요??

2024-11-26 05:34 UTC, hyobiin9 commented on test.http
> +GET http://ec2-15-165-57-191.ap-northeast-2.compute.amazonaws.com/challenges
도엽님 test.http 파일은 gitignore 파일에 올리셔서 안 올라오게 설정 부탁드립니다!!

2024-11-26 06:54 UTC, merged